version: "3.9"

services:
  # ----------------------
  # Backend FastAPI
  # ----------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forga_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://gsmi_admin:123@db:5432/forga_db
    restart: unless-stopped

  # ----------------------
  # Frontend React
  # ----------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forga_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"  # pour hot-reload sous Docker
    command: npm start
    restart: unless-stopped
